// <auto-generated />
using System;
using APIWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIWeb.Migrations
{
    [DbContext(typeof(context))]
    partial class contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIWeb.Models.hardware", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HardwareName");

                    b.Property<int>("UserId");

                    b.Property<long?>("usersId");

                    b.HasKey("Id");

                    b.HasIndex("usersId");

                    b.ToTable("hardware");
                });

            modelBuilder.Entity("APIWeb.Models.software", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SoftwareName");

                    b.Property<int>("UserId");

                    b.Property<long?>("usersId");

                    b.HasKey("Id");

                    b.HasIndex("usersId");

                    b.ToTable("software");
                });

            modelBuilder.Entity("APIWeb.Models.user", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("LastSessionDateTime");

                    b.Property<string>("Name");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("APIWeb.Models.hardware", b =>
                {
                    b.HasOne("APIWeb.Models.user", "users")
                        .WithMany("hardware")
                        .HasForeignKey("usersId");
                });

            modelBuilder.Entity("APIWeb.Models.software", b =>
                {
                    b.HasOne("APIWeb.Models.user", "users")
                        .WithMany("software")
                        .HasForeignKey("usersId");
                });
#pragma warning restore 612, 618
        }
    }
}
